version: "3"

services:
  db:
    build: ./database
    environment:
      POSTGRES_DB: ynchacks
      POSTGRES_USER: ynchacks
      POSTGRES_PASSWORD: password
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    # volumes:
    #   - ./backups:/postgresql/
    command: -p 5433

  flask:
    image: python:3-stretch
    command: sh -c "pip3 install SQLAlchemy psycopg2 pytz Flask Flask-SQLAlchemy && python -m server "
    environment:
      - PORT=9000
      - FLASK_ENV=development
    ports:
      - "9000:9000"
    working_dir: /root/py1
    volumes:
      - ./py1:/root/py1:cached # <--- This will map ./py1 to /root/py1 inside the container.

